#include <exception>

int main(int argc, char * argv[])
{
	std::exception_ptr e;

	return 0;
}
